# Site
repository: lucadev/lucadev.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Luca Kröger
title: Student/Consultant @ mindsquare AG
email: l.kroeger01@gmail.com
website: lucadev.de

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  LucaDev
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: l_uuc
linkedin_username: lucakroeger
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Luca and I'm a German student working at mindsquare. I love playing with new technologies and creating cool stuff. I have worked in and lead a number of teams, to do so.

  I am most skilled in: <mark>DevOps</mark> and <mark>Eating Pizza</mark>

content:
  #- title: Projects
  #  layout: list
  #  content:
  #    - layout: top-middle
  #      title: Super awesome project
  #      link: github.com/sproogen
  #      # link_text: Project Website
  #      additional_links:
  #        - title:  sproogen/modern-resume-theme
  #          icon: fab fa-github
  #          url: github.com/sproogen/modern-resume-theme
  #        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #        #   icon: fab fa-github
  #        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #      quote: >
  #        This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #      description: | # this will include new lines to allow paragraphs
  #        I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: mindsquare AG
        link: mindsquare.de
        sub_title: IT Consultant
        caption: October 2020 - Present
        quote: >
          Solving problems and helping our customers to get their IT working for instead of against them.
        description: | # this will include new lines to allow paragraphs
            TODO
      - layout: left
        title: Scrayos UG (haftungsbeschränkt)
        link: scrayos.net
        sub_title: Freelance
        caption: August 2017 - April 2019, October 2020 - Present
        quote: >
          Solving problems and getting non cloud-native applications into the cloud. 
        description: | # this will include new lines to allow paragraphs
            TODO
      - layout: left
        title: BOGE Compressed Air Systems GmbH & Co. KG
        link: scrayos.net
        sub_title: Intern
        caption: June 2017 - Juli 2017
        quote: >
          Gaining first experiances in a IT department
        description: | # this will include new lines to allow paragraphs
            TODO


  - title: Education
    layout: list
    content:
      - layout: left
        title: Bielefeld University of Applied Sciences
        caption: October 2020 - 2023
        sub_title: BSc Computer Science
        quote: >
          The Bielefeld University of Applied Sciences (Fachhochschule Bielefeld) is the second largest education institution in Bielefeld, Germany.
        description: |
          TODO
      - layout: left
        title: Widukind Gymnasium Enger
        caption: - 2020
        sub_title: Abitur 1.9
        quote: >
          The Widukind Gymnasium in Enger is 
        description: |
          TODO

  - title: Certifications
    layout: list
    content:
      - layout: left
        title: ITIL v3 Foundation
        link: https://www.peoplecert.org/for-corporations/certificate-verification-service
        sub_title: IT Infrastructure Library
        caption: 2020
        description: |
            TODO
            
  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in software and systems engineering some of my other interests and hobbies are:
      - Cooking
      - Driving
      - Partying

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
